from typing import Any

from pyarrow._hdfsio import HdfsFile as HdfsFile
from pyarrow._hdfsio import have_libhdfs as have_libhdfs
from pyarrow.ipc import Message as Message
from pyarrow.ipc import MessageReader as MessageReader
from pyarrow.ipc import MetadataVersion as MetadataVersion
from pyarrow.ipc import RecordBatchFileReader as RecordBatchFileReader
from pyarrow.ipc import RecordBatchFileWriter as RecordBatchFileWriter
from pyarrow.ipc import RecordBatchStreamReader as RecordBatchStreamReader
from pyarrow.ipc import RecordBatchStreamWriter as RecordBatchStreamWriter
from pyarrow.ipc import deserialize_pandas as deserialize_pandas
from pyarrow.ipc import serialize_pandas as serialize_pandas
from pyarrow.lib import NA as NA
from pyarrow.lib import Array as Array
from pyarrow.lib import ArrowCancelled as ArrowCancelled
from pyarrow.lib import ArrowCapacityError as ArrowCapacityError
from pyarrow.lib import ArrowException as ArrowException
from pyarrow.lib import ArrowIndexError as ArrowIndexError
from pyarrow.lib import ArrowInvalid as ArrowInvalid
from pyarrow.lib import ArrowIOError as ArrowIOError
from pyarrow.lib import ArrowKeyError as ArrowKeyError
from pyarrow.lib import ArrowMemoryError as ArrowMemoryError
from pyarrow.lib import ArrowNotImplementedError as ArrowNotImplementedError
from pyarrow.lib import ArrowSerializationError as ArrowSerializationError
from pyarrow.lib import ArrowTypeError as ArrowTypeError
from pyarrow.lib import BaseExtensionType as BaseExtensionType
from pyarrow.lib import BinaryArray as BinaryArray
from pyarrow.lib import BinaryScalar as BinaryScalar
from pyarrow.lib import BooleanArray as BooleanArray
from pyarrow.lib import BooleanScalar as BooleanScalar
from pyarrow.lib import Buffer as Buffer
from pyarrow.lib import BufferedInputStream as BufferedInputStream
from pyarrow.lib import BufferedOutputStream as BufferedOutputStream
from pyarrow.lib import BufferOutputStream as BufferOutputStream
from pyarrow.lib import BufferReader as BufferReader
from pyarrow.lib import BuildInfo as BuildInfo
from pyarrow.lib import ChunkedArray as ChunkedArray
from pyarrow.lib import Codec as Codec
from pyarrow.lib import CompressedInputStream as CompressedInputStream
from pyarrow.lib import CompressedOutputStream as CompressedOutputStream
from pyarrow.lib import DataType as DataType
from pyarrow.lib import Date32Array as Date32Array
from pyarrow.lib import Date32Scalar as Date32Scalar
from pyarrow.lib import Date64Array as Date64Array
from pyarrow.lib import Date64Scalar as Date64Scalar
from pyarrow.lib import Decimal128Array as Decimal128Array
from pyarrow.lib import Decimal128Scalar as Decimal128Scalar
from pyarrow.lib import Decimal128Type as Decimal128Type
from pyarrow.lib import Decimal256Array as Decimal256Array
from pyarrow.lib import Decimal256Scalar as Decimal256Scalar
from pyarrow.lib import Decimal256Type as Decimal256Type
from pyarrow.lib import DenseUnionType as DenseUnionType
from pyarrow.lib import DeserializationCallbackError as DeserializationCallbackError
from pyarrow.lib import DictionaryArray as DictionaryArray
from pyarrow.lib import DictionaryMemo as DictionaryMemo
from pyarrow.lib import DictionaryScalar as DictionaryScalar
from pyarrow.lib import DictionaryType as DictionaryType
from pyarrow.lib import DoubleScalar as DoubleScalar
from pyarrow.lib import DurationArray as DurationArray
from pyarrow.lib import DurationScalar as DurationScalar
from pyarrow.lib import DurationType as DurationType
from pyarrow.lib import ExtensionArray as ExtensionArray
from pyarrow.lib import ExtensionScalar as ExtensionScalar
from pyarrow.lib import ExtensionType as ExtensionType
from pyarrow.lib import Field as Field
from pyarrow.lib import FixedSizeBinaryArray as FixedSizeBinaryArray
from pyarrow.lib import FixedSizeBinaryScalar as FixedSizeBinaryScalar
from pyarrow.lib import FixedSizeBinaryType as FixedSizeBinaryType
from pyarrow.lib import FixedSizeBufferWriter as FixedSizeBufferWriter
from pyarrow.lib import FixedSizeListArray as FixedSizeListArray
from pyarrow.lib import FixedSizeListScalar as FixedSizeListScalar
from pyarrow.lib import FixedSizeListType as FixedSizeListType
from pyarrow.lib import FloatingPointArray as FloatingPointArray
from pyarrow.lib import FloatScalar as FloatScalar
from pyarrow.lib import HalfFloatScalar as HalfFloatScalar
from pyarrow.lib import Int8Array as Int8Array
from pyarrow.lib import Int8Scalar as Int8Scalar
from pyarrow.lib import Int16Array as Int16Array
from pyarrow.lib import Int16Scalar as Int16Scalar
from pyarrow.lib import Int32Array as Int32Array
from pyarrow.lib import Int32Scalar as Int32Scalar
from pyarrow.lib import Int64Array as Int64Array
from pyarrow.lib import Int64Scalar as Int64Scalar
from pyarrow.lib import IntegerArray as IntegerArray
from pyarrow.lib import KeyValueMetadata as KeyValueMetadata
from pyarrow.lib import LargeBinaryArray as LargeBinaryArray
from pyarrow.lib import LargeBinaryScalar as LargeBinaryScalar
from pyarrow.lib import LargeListArray as LargeListArray
from pyarrow.lib import LargeListScalar as LargeListScalar
from pyarrow.lib import LargeListType as LargeListType
from pyarrow.lib import LargeStringArray as LargeStringArray
from pyarrow.lib import LargeStringScalar as LargeStringScalar
from pyarrow.lib import ListArray as ListArray
from pyarrow.lib import ListScalar as ListScalar
from pyarrow.lib import ListType as ListType
from pyarrow.lib import LoggingMemoryPool as LoggingMemoryPool
from pyarrow.lib import MapArray as MapArray
from pyarrow.lib import MapScalar as MapScalar
from pyarrow.lib import MapType as MapType
from pyarrow.lib import MemoryMappedFile as MemoryMappedFile
from pyarrow.lib import MemoryPool as MemoryPool
from pyarrow.lib import MockOutputStream as MockOutputStream
from pyarrow.lib import MonthDayNano as MonthDayNano
from pyarrow.lib import MonthDayNanoIntervalArray as MonthDayNanoIntervalArray
from pyarrow.lib import MonthDayNanoIntervalScalar as MonthDayNanoIntervalScalar
from pyarrow.lib import NativeFile as NativeFile
from pyarrow.lib import NullArray as NullArray
from pyarrow.lib import NullScalar as NullScalar
from pyarrow.lib import NumericArray as NumericArray
from pyarrow.lib import OSFile as OSFile
from pyarrow.lib import ProxyMemoryPool as ProxyMemoryPool
from pyarrow.lib import PyExtensionType as PyExtensionType
from pyarrow.lib import PythonFile as PythonFile
from pyarrow.lib import RecordBatch as RecordBatch
from pyarrow.lib import RecordBatchReader as RecordBatchReader
from pyarrow.lib import ResizableBuffer as ResizableBuffer
from pyarrow.lib import RuntimeInfo as RuntimeInfo
from pyarrow.lib import Scalar as Scalar
from pyarrow.lib import Schema as Schema
from pyarrow.lib import SerializationCallbackError as SerializationCallbackError
from pyarrow.lib import SparseCOOTensor as SparseCOOTensor
from pyarrow.lib import SparseCSCMatrix as SparseCSCMatrix
from pyarrow.lib import SparseCSFTensor as SparseCSFTensor
from pyarrow.lib import SparseCSRMatrix as SparseCSRMatrix
from pyarrow.lib import SparseUnionType as SparseUnionType
from pyarrow.lib import StringArray as StringArray
from pyarrow.lib import StringScalar as StringScalar
from pyarrow.lib import StructArray as StructArray
from pyarrow.lib import StructScalar as StructScalar
from pyarrow.lib import StructType as StructType
from pyarrow.lib import Table as Table
from pyarrow.lib import TableGroupBy as TableGroupBy
from pyarrow.lib import Tensor as Tensor
from pyarrow.lib import Time32Array as Time32Array
from pyarrow.lib import Time32Scalar as Time32Scalar
from pyarrow.lib import Time32Type as Time32Type
from pyarrow.lib import Time64Array as Time64Array
from pyarrow.lib import Time64Scalar as Time64Scalar
from pyarrow.lib import Time64Type as Time64Type
from pyarrow.lib import TimestampArray as TimestampArray
from pyarrow.lib import TimestampScalar as TimestampScalar
from pyarrow.lib import TimestampType as TimestampType
from pyarrow.lib import TransformInputStream as TransformInputStream
from pyarrow.lib import UInt8Array as UInt8Array
from pyarrow.lib import UInt8Scalar as UInt8Scalar
from pyarrow.lib import UInt16Array as UInt16Array
from pyarrow.lib import UInt16Scalar as UInt16Scalar
from pyarrow.lib import UInt32Array as UInt32Array
from pyarrow.lib import UInt32Scalar as UInt32Scalar
from pyarrow.lib import UInt64Array as UInt64Array
from pyarrow.lib import UInt64Scalar as UInt64Scalar
from pyarrow.lib import UnionArray as UnionArray
from pyarrow.lib import UnionScalar as UnionScalar
from pyarrow.lib import UnionType as UnionType
from pyarrow.lib import UnknownExtensionType as UnknownExtensionType
from pyarrow.lib import VersionInfo as VersionInfo
from pyarrow.lib import allocate_buffer as allocate_buffer
from pyarrow.lib import array as array
from pyarrow.lib import binary as binary
from pyarrow.lib import bool_ as bool_
from pyarrow.lib import chunked_array as chunked_array
from pyarrow.lib import compress as compress
from pyarrow.lib import concat_arrays as concat_arrays
from pyarrow.lib import concat_tables as concat_tables
from pyarrow.lib import cpp_build_info as cpp_build_info
from pyarrow.lib import cpp_version as cpp_version
from pyarrow.lib import cpp_version_info as cpp_version_info
from pyarrow.lib import cpu_count as cpu_count
from pyarrow.lib import create_memory_map as create_memory_map
from pyarrow.lib import date32 as date32
from pyarrow.lib import date64 as date64
from pyarrow.lib import decimal128 as decimal128
from pyarrow.lib import decimal256 as decimal256
from pyarrow.lib import decompress as decompress
from pyarrow.lib import default_memory_pool as default_memory_pool
from pyarrow.lib import dense_union as dense_union
from pyarrow.lib import deserialize as deserialize
from pyarrow.lib import deserialize_components as deserialize_components
from pyarrow.lib import deserialize_from as deserialize_from
from pyarrow.lib import dictionary as dictionary
from pyarrow.lib import duration as duration
from pyarrow.lib import enable_signal_handlers as enable_signal_handlers
from pyarrow.lib import field as field
from pyarrow.lib import float16 as float16
from pyarrow.lib import float32 as float32
from pyarrow.lib import float64 as float64
from pyarrow.lib import foreign_buffer as foreign_buffer
from pyarrow.lib import from_numpy_dtype as from_numpy_dtype
from pyarrow.lib import infer_type as infer_type
from pyarrow.lib import input_stream as input_stream
from pyarrow.lib import int8 as int8
from pyarrow.lib import int16 as int16
from pyarrow.lib import int32 as int32
from pyarrow.lib import int64 as int64
from pyarrow.lib import io_thread_count as io_thread_count
from pyarrow.lib import jemalloc_memory_pool as jemalloc_memory_pool
from pyarrow.lib import jemalloc_set_decay_ms as jemalloc_set_decay_ms
from pyarrow.lib import large_binary as large_binary
from pyarrow.lib import large_list as large_list
from pyarrow.lib import large_string as large_string
from pyarrow.lib import large_utf8 as large_utf8
from pyarrow.lib import list_ as list_
from pyarrow.lib import log_memory_allocations as log_memory_allocations
from pyarrow.lib import logging_memory_pool as logging_memory_pool
from pyarrow.lib import map_ as map_
from pyarrow.lib import memory_map as memory_map
from pyarrow.lib import mimalloc_memory_pool as mimalloc_memory_pool
from pyarrow.lib import month_day_nano_interval as month_day_nano_interval
from pyarrow.lib import null as null
from pyarrow.lib import nulls as nulls
from pyarrow.lib import output_stream as output_stream
from pyarrow.lib import proxy_memory_pool as proxy_memory_pool
from pyarrow.lib import py_buffer as py_buffer
from pyarrow.lib import read_serialized as read_serialized
from pyarrow.lib import record_batch as record_batch
from pyarrow.lib import register_extension_type as register_extension_type
from pyarrow.lib import repeat as repeat
from pyarrow.lib import runtime_info as runtime_info
from pyarrow.lib import scalar as scalar
from pyarrow.lib import schema as schema
from pyarrow.lib import serialize as serialize
from pyarrow.lib import serialize_to as serialize_to
from pyarrow.lib import set_cpu_count as set_cpu_count
from pyarrow.lib import set_io_thread_count as set_io_thread_count
from pyarrow.lib import set_memory_pool as set_memory_pool
from pyarrow.lib import sparse_union as sparse_union
from pyarrow.lib import string as string
from pyarrow.lib import struct as struct
from pyarrow.lib import supported_memory_backends as supported_memory_backends
from pyarrow.lib import system_memory_pool as system_memory_pool
from pyarrow.lib import table as table
from pyarrow.lib import time32 as time32
from pyarrow.lib import time64 as time64
from pyarrow.lib import timestamp as timestamp
from pyarrow.lib import total_allocated_bytes as total_allocated_bytes
from pyarrow.lib import transcoding_input_stream as transcoding_input_stream
from pyarrow.lib import type_for_alias as type_for_alias
from pyarrow.lib import uint8 as uint8
from pyarrow.lib import uint16 as uint16
from pyarrow.lib import uint32 as uint32
from pyarrow.lib import uint64 as uint64
from pyarrow.lib import unify_schemas as unify_schemas
from pyarrow.lib import union as union
from pyarrow.lib import unregister_extension_type as unregister_extension_type
from pyarrow.lib import utf8 as utf8
from pyarrow.serialization import default_serialization_context as default_serialization_context
from pyarrow.serialization import (
    register_default_serialization_handlers as register_default_serialization_handlers,
)
from pyarrow.serialization import (
    register_torch_serialization_handlers as register_torch_serialization_handlers,
)

from . import filesystem as filesystem
from . import hdfs as hdfs
from . import ipc as ipc
from . import serialization as serialization
from . import types as types
from . import util as util

def show_versions() -> None: ...
def show_info() -> None: ...
def __getattr__(name: str) -> Any: ...
def get_include() -> str: ...
def get_libraries() -> tuple[str, str]: ...
def create_library_symlinks() -> None: ...
def get_library_dirs() -> list[str]: ...
