from typing import (
    Any,
    Callable,
)

import pyarrow._fs

_stringify_path: Callable

class HadoopFileSystem(pyarrow._fs.FileSystem):
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def _reconstruct(cls, typecls, kwargs) -> Any: ...
    def from_uri(self, uri) -> Any: ...
    def __reduce__(self) -> Any: ...

def frombytes(*args, **kwargs) -> Any: ...
def tobytes(o) -> Any: ...
