from typing import Any
from typing import Callable

import pyarrow._fs

_stringify_path: Callable

class HadoopFileSystem(pyarrow._fs.FileSystem):
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def _reconstruct(cls, typecls, kwargs) -> Any: ...
    @classmethod
    def from_uri(cls, uri) -> HadoopFileSystem: ...
    def __reduce__(self) -> Any: ...

def frombytes(*args, **kwargs) -> Any: ...
def tobytes(o) -> Any: ...
