from typing import (
    Any,
    ClassVar,
    Optional,
)
from io import IOBase
from pyarrow import NativeFile

import pyarrow.lib

class ParseOptions(pyarrow.lib._Weakrefable):
    __slots__: ClassVar[tuple] = ...
    explicit_schema: Optional[pyarrow.lib.Schema] = ...
    newlines_in_values: Optional[bool] = ...
    unexpected_field_behavior: str = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class ReadOptions(pyarrow.lib._Weakrefable):
    __slots__: ClassVar[tuple] = ...
    block_size: Optional[bool] = ...
    use_threads: Optional[int] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

def read_json(
    input_file: str | NativeFile | IOBase, read_options: ReadOptions = ..., parse_options: ParseOptions = ..., memory_pool: pyarrow.lib.MemoryPool = ...
) -> pyarrow.lib.Table: ...
