from typing import Any

import pyarrow.lib

_stringify_path: function

class ORCReader(pyarrow.lib._Weakrefable):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def compression(self) -> Any: ...
    def compression_size(self) -> Any: ...
    def content_length(self) -> Any: ...
    def file_footer_length(self) -> Any: ...
    def file_length(self) -> Any: ...
    def file_postscript_length(self) -> Any: ...
    def file_version(self) -> Any: ...
    def metadata(self) -> Any: ...
    def nrows(self) -> Any: ...
    def nstripe_statistics(self) -> Any: ...
    def nstripes(self) -> Any: ...
    def open(self, source, booluse_memory_map=...) -> Any: ...
    def read(self, columns=...) -> Any: ...
    def read_stripe(self, n, columns=...) -> Any: ...
    def row_index_stride(self) -> Any: ...
    def schema(self) -> Any: ...
    def serialized_file_tail(self) -> Any: ...
    def software_version(self) -> Any: ...
    def stripe_statistics_length(self) -> Any: ...
    def writer(self) -> Any: ...
    def writer_version(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class ORCWriter(pyarrow.lib._Weakrefable):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def close(self) -> Any: ...
    def open(self, *args, **kwargs) -> Any: ...
    def write(self, Tabletable) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def frombytes(*args, **kwargs) -> Any: ...
def tobytes(o) -> Any: ...
