from .lib import _Weakrefable

class CryptoFactory(_Weakrefable): ...
class EncryptionConfiguration(_Weakrefable): ...
class DecryptionConfiguration(_Weakrefable): ...
class KmsConnectionConfig(_Weakrefable): ...
