from pyarrow.lib import DataType

def is_null(t: DataType) -> bool: ...
def is_boolean(t: DataType) -> bool: ...
def is_integer(t: DataType) -> bool: ...
def is_signed_integer(t: DataType) -> bool: ...
def is_unsigned_integer(t: DataType) -> bool: ...
def is_int8(t: DataType) -> bool: ...
def is_int16(t: DataType) -> bool: ...
def is_int32(t: DataType) -> bool: ...
def is_int64(t: DataType) -> bool: ...
def is_uint8(t: DataType) -> bool: ...
def is_uint16(t: DataType) -> bool: ...
def is_uint32(t: DataType) -> bool: ...
def is_uint64(t: DataType) -> bool: ...
def is_floating(t: DataType) -> bool: ...
def is_float16(t: DataType) -> bool: ...
def is_float32(t: DataType) -> bool: ...
def is_float64(t: DataType) -> bool: ...
def is_list(t: DataType) -> bool: ...
def is_large_list(t: DataType) -> bool: ...
def is_fixed_size_list(t: DataType) -> bool: ...
def is_list_view(t: DataType) -> bool: ...
def is_large_list_view(t: DataType) -> bool: ...
def is_struct(t: DataType) -> bool: ...
def is_union(t: DataType) -> bool: ...
def is_nested(t: DataType) -> bool: ...
def is_run_end_encoded(t: DataType) -> bool: ...
def is_temporal(t: DataType) -> bool: ...
def is_timestamp(t: DataType) -> bool: ...
def is_duration(t: DataType) -> bool: ...
def is_time(t: DataType) -> bool: ...
def is_time32(t: DataType) -> bool: ...
def is_time64(t: DataType) -> bool: ...
def is_binary(t: DataType) -> bool: ...
def is_large_binary(t: DataType) -> bool: ...
def is_unicode(t: DataType) -> bool: ...
def is_string(t: DataType) -> bool: ...
def is_large_unicode(t: DataType) -> bool: ...
def is_large_string(t: DataType) -> bool: ...
def is_fixed_size_binary(t: DataType) -> bool: ...
def is_binary_view(t: DataType) -> bool: ...
def is_string_view(t: DataType) -> bool: ...
def is_date(t: DataType) -> bool: ...
def is_date32(t: DataType) -> bool: ...
def is_date64(t: DataType) -> bool: ...
def is_map(t: DataType) -> bool: ...
def is_decimal(t: DataType) -> bool: ...
def is_decimal32(t: DataType) -> bool: ...
def is_decimal64(t: DataType) -> bool: ...
def is_decimal128(t: DataType) -> bool: ...
def is_decimal256(t: DataType) -> bool: ...
def is_dictionary(t: DataType) -> bool: ...
def is_interval(t: DataType) -> bool: ...
def is_primitive(t: DataType) -> bool: ...

__all__ = [
    "is_binary",
    "is_binary_view",
    "is_boolean",
    "is_date",
    "is_date32",
    "is_date64",
    "is_decimal",
    "is_decimal128",
    "is_decimal256",
    "is_decimal32",
    "is_decimal64",
    "is_dictionary",
    "is_duration",
    "is_fixed_size_binary",
    "is_fixed_size_list",
    "is_float16",
    "is_float32",
    "is_float64",
    "is_floating",
    "is_int16",
    "is_int32",
    "is_int64",
    "is_int8",
    "is_integer",
    "is_interval",
    "is_large_binary",
    "is_large_list",
    "is_large_list_view",
    "is_large_string",
    "is_large_unicode",
    "is_list",
    "is_list_view",
    "is_map",
    "is_nested",
    "is_null",
    "is_primitive",
    "is_run_end_encoded",
    "is_signed_integer",
    "is_string",
    "is_string_view",
    "is_struct",
    "is_temporal",
    "is_time",
    "is_time32",
    "is_time64",
    "is_timestamp",
    "is_uint16",
    "is_uint32",
    "is_uint64",
    "is_uint8",
    "is_unicode",
    "is_union",
    "is_unsigned_integer",
]
