name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  taplo:
    name: taplo
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: uncenter/setup-taplo@v1
        with:
          version: "0.9.3"
      - run: taplo fmt --check

  pyright:
    name: pyright
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install pandas numpy scipy sparse
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v2
